import { previewSchedulePatch, SCHEDULE_CSV_HEADER, SCHEDULE_CSV_LIMIT, UNPUBLISHED_ROOM } from '../src/lib/schedulePatch';
import { parseAdminImport } from '../src/lib/adminImport';
import courses from '../src/semester/courses.json';
import sch from '../src/semester/sch.json';
import type { Course } from '../src/types';

const published = { 'courses.json': courses as Course[], 'sch.json': sch as Course[] };
const before = JSON.stringify(published);
const csv = (...rows: string[]) => `\uFEFF${SCHEDULE_CSV_HEADER}\r\n${rows.join('\r\n')}`;
const check = (ok: unknown, message: string) => { if (!ok) throw new Error(message); };
const original = published['courses.json'].find(c => c.code === 'CSAI 205')!;
const firstLecture = original.instructors.flatMap(i => i.lectures).find(m => m.sec === '03')!;
const originalInstructor = original.instructors.find(i => i.lectures.includes(firstLecture))!.name;
const row = 'CSAI 205,Lecture,03,Tue,10:00,12:00,G090-B';
const updated = previewSchedulePatch(csv(row), published);
check(updated.read === 1 && updated.applied === 1 && updated.unchanged === 0 && updated.excluded === 0, 'Valid CSV update was not applied');
check(updated.changes[0].file === 'courses.json' && updated.changes[0].before.includes(firstLecture.room) && updated.changes[0].after.includes('G090-B'), 'Before/after is incomplete');
const resulting = updated.next['courses.json'].find(c => c.id === original.id)!;
check(resulting.code === original.code && resulting.name === original.name && resulting.credits === original.credits && resulting.instructors.find(i => i.lectures.some(m => m.sec === '03'))!.name === originalInstructor, 'Course metadata or instructor changed');
check(resulting.instructors.flatMap(i => i.lectures).find(m => m.sec === '03')!.start === 600 && resulting.instructors.flatMap(i => i.lectures).find(m => m.sec === '03')!.end === 720, 'Minute boundaries were rounded');
check(JSON.stringify(published) === before, 'Published input was mutated');
const repeat = previewSchedulePatch(csv(row, row), published);
check(repeat.read === 2 && repeat.applied === 1 && repeat.excluded === 1 && repeat.issues[0].kind === 'duplicate', 'Identical duplicate was silently discarded or applied twice');
const unchanged = previewSchedulePatch(csv(`CSAI 205,Lecture,03,${firstLecture.day},${String(Math.floor(firstLecture.start / 60)).padStart(2, '0')}:00,${String(Math.floor(firstLecture.end / 60)).padStart(2, '0')}:00,${firstLecture.room}`), published);
check(unchanged.unchanged === 1 && unchanged.applied === 0, 'Identical published row should remain unchanged');
const multiple = previewSchedulePatch(csv(row, 'CSAI 205,Lecture,03,Wed,10:00,12:00,G006-B'), published);
check(multiple.applied === 0 && multiple.excluded === 2 && multiple.issues.every(issue => issue.kind === 'multiple meetings'), 'Multiple times for the same section should be held for review');
const conflict = previewSchedulePatch(csv(row, 'CSAI 205,Lecture,03,Tue,10:00,12:00,G020-A'), published);
check(conflict.applied === 0 && conflict.issues.every(issue => issue.kind === 'conflict'), 'Conflicting room for one time should be blocked');
const incomplete = previewSchedulePatch(csv(row, 'CSAI 205,Lecture,03,Tue,10:00,12:00,'), published);
check(incomplete.applied === 0 && incomplete.excluded === 2 && incomplete.issues.some(issue => issue.reason.includes('Room extraction')), 'Incomplete row must block another row for the same section');
const blankRoom = previewSchedulePatch(csv('CSAI 205,Lecture,03,Tue,10:00,12:00,'), published);
check(blankRoom.applied === 0 && JSON.stringify(blankRoom.next) === before, 'Blank room erased published data');
const officialUnpublished = previewSchedulePatch(csv(`CSAI 205,Lecture,03,Tue,10:00,12:00,${UNPUBLISHED_ROOM}`), published);
check(officialUnpublished.applied === 1 && officialUnpublished.next['courses.json'].find(c => c.id === original.id)!.instructors.flatMap(i => i.lectures).find(m => m.sec === '03')!.room === '', 'Confirmed unpublished room was not cleared explicitly');
const zero = previewSchedulePatch(csv('CSAI 205,Lecture,3,Tue,10:00,12:00,G006-B', row), published);
check(zero.applied === 1 && zero.excluded === 1 && zero.issues.some(issue => issue.reason.includes('Section 3')), 'Section 3 must not match section 03');
const unknown = previewSchedulePatch(csv('FAKE 999,Lecture,01,Tue,10:00,12:00,G006-B','CSAI 205,Lecture,99,Tue,10:00,12:00,G006-B'), published);
check(unknown.excluded === 2 && unknown.applied === 0 && unknown.issues.every(issue => issue.kind === 'missing'), 'Unknown course/section should not be created');
const bad = previewSchedulePatch(csv('CSAI 205,Seminar,03,Tue,10:00,12:00,G006-B','CSAI 205,Lecture,03,Fri,10:00,12:00,G006-B','CSAI 205,Lecture,03,Tue,10:00,11:59,G006-B'), published);
check(bad.applied === 0 && bad.excluded === 3, 'Invalid component/day or inclusive :59 time was accepted');
const size = previewSchedulePatch(csv(row) + ' '.repeat(SCHEDULE_CSV_LIMIT), published);
check(!!size.fatal && size.applied === 0, 'Over-limit CSV was partially staged');
const schCourse = published['sch.json'].find(c => c.instructors.some(i => i.lectures.length))!;
const schMeeting = schCourse.instructors.flatMap(i => i.lectures)[0];
const routed = previewSchedulePatch(csv(row, `${schCourse.code},Lecture,${schMeeting.sec},Wed,08:00,10:00,G019-B`), published);
check(routed.changes.some(c => c.file === 'courses.json') && routed.changes.some(c => c.file === 'sch.json') && routed.applied === 2, 'One CSV did not route rows across both files');
const ambiguousData = structuredClone(published);
ambiguousData['courses.json'].find(c => c.id === original.id)!.instructors.push({ name: 'Second instructor', lectures: [{ ...firstLecture }], labs: [], tutorials: [] });
const ambiguous = previewSchedulePatch(csv(row), ambiguousData);
check(ambiguous.applied === 0 && ambiguous.issues[0].kind === 'ambiguous', 'Multiple instructor matches should require review');
const duplicateCourse = structuredClone(published);
duplicateCourse['sch.json'].push(structuredClone(original));
check(previewSchedulePatch(csv(row), duplicateCourse).issues[0].kind === 'ambiguous', 'Duplicate course across files should not be silently routed');
const oldHeader = parseAdminImport('courseCode,subtype,section,day,start,end,room,instructor\nCSAI 205,Lecture,03,Tue,10:00,12:00,G006-B,Mohamed Maher Ata\nCSAI 205,Lecture,03,Tue,10:00,12:00,G006-B,Mohamed Maher Ata', '', 'csv');
check(oldHeader.rows.length === 1 && oldHeader.warnings.length === 1 && oldHeader.warnings[0].includes('identical'), 'Legacy importer must distinguish identical repeats');
console.log('Schedule patch: scoped fields, both files, zero-padded sections, duplicates, ambiguity and incomplete sources OK');
