import { JSDOM } from 'jsdom';
const dom = new JSDOM('<div id="root"></div>', { url: 'http://localhost/' });
const globalValues = globalThis as unknown as Record<string, unknown>;
Object.assign(globalValues, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, IS_REACT_ACT_ENVIRONMENT: true });
import React, { act } from 'react';
import { createRoot } from 'react-dom/client';
import { Timetable } from '../src/components/Timetable';
import { COURSE_BY_ID } from '../src/data/courses';
const course = COURSE_BY_ID.csai201;
const meeting = course.instructors[0].lectures[0];
const root = createRoot(dom.window.document.getElementById('root')!);
act(() => root.render(<Timetable events={[{ course, meeting }]} hiddenCount={0} />));
const card = dom.window.document.querySelector(`button[aria-label="View ${course.code} Lecture section ${meeting.sec} details"]`) as HTMLButtonElement;
if (!card) throw new Error('The session cannot be opened');
act(() => card.click());
const dialog = dom.window.document.querySelector('[role="dialog"]');
if (!dialog?.textContent?.includes(course.name) || !dialog.textContent.includes(course.instructors[0].name) || !dialog.textContent.includes(meeting.room)) throw new Error('Published meeting details are missing');
act(() => (dom.window.document.querySelector('[aria-label="Close course details"]') as HTMLButtonElement).click());
if (dom.window.document.querySelector('[role="dialog"]')) throw new Error('The details dialog did not close');
act(() => root.unmount());
console.log('Timetable meeting details: open, published data and close OK');
